{
  "formatVersion": "1.1",
  "component": {
    "group": "com.neasaa",
    "module": "neasaa-utils",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "lu27mpeewbddjaik6zz2jj47le"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "slf4j-api",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.8.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "commons-io",
              "type": "jar",
              "extension": "jar"
            }
          }
        }
      ],
      "files": [
        {
          "name": "neasaa-utils-1.0.0.jar",
          "url": "neasaa-utils-1.0.0.jar",
          "size": 16281,
          "sha512": "3ef84aab498337103f60dd238a8884c2be312b1716a6fb70cce35d07749d95acf854b7c966dcb278216f16778841c59985a47ccc7ca4907d0f5f4b48414436e3",
          "sha256": "ba6e00a8c75d8966ad817f7ce5ba4fea7575a1453825580e100127edfd730111",
          "sha1": "4c36ca1152aa2c1d8c08c876300e15ed86f16a95",
          "md5": "fa71727cbd8a6f163667a7dd833dc459"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "slf4j-api",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.8.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "commons-io",
              "type": "jar",
              "extension": "jar"
            }
          }
        }
      ],
      "files": [
        {
          "name": "neasaa-utils-1.0.0.jar",
          "url": "neasaa-utils-1.0.0.jar",
          "size": 16281,
          "sha512": "3ef84aab498337103f60dd238a8884c2be312b1716a6fb70cce35d07749d95acf854b7c966dcb278216f16778841c59985a47ccc7ca4907d0f5f4b48414436e3",
          "sha256": "ba6e00a8c75d8966ad817f7ce5ba4fea7575a1453825580e100127edfd730111",
          "sha1": "4c36ca1152aa2c1d8c08c876300e15ed86f16a95",
          "md5": "fa71727cbd8a6f163667a7dd833dc459"
        }
      ]
    }
  ]
}
