package com.neasaa.codegenerator.jdbc;

import java.util.ArrayList;
import java.util.List;

import com.neasaa.util.StringUtils;

/**
 * This class builds and create prepared statement for insert operation.
 * 
 * @author Vijay Garothaya
 * @version 1.0 Oct 8, 2018
 */
public class InsertSqlStatementGenerator {

	/**
	 * Generate Insert SQL statement.
	 * 
	 * @param aTableOperation
	 * @param columnsToAddInInsertStatement
	 * @return
	 * @throws Exception
	 */
	public static String buildInsertSqlStatement ( TableDefinition tableDefinition ) throws Exception {

		List<ColumnDefinition> columnsToAddInInsertStatement = new ArrayList<>();
		// Loop thru all column and create a primary column list
		for ( ColumnDefinition columnDefinition : tableDefinition.getColumnDefinitions() ) {
			// continue if this column to ignore on target database.
			if ( columnDefinition.isIgnoreColumn() ) {
				continue;
			}
			if ( columnDefinition.isAutoGenerated()) {
				continue;
			}
			columnsToAddInInsertStatement.add( columnDefinition );
		}
		
		

		StringBuilder query = new StringBuilder( "INSERT INTO " );
		if ( !StringUtils.isEmpty( tableDefinition.getSchemaName() ) ) {
			query.append( tableDefinition.getSchemaName() ).append( "." );
		}
		query.append( tableDefinition.getTableName() );

		StringBuilder columnNameList = new StringBuilder();
		StringBuilder columnValueList = new StringBuilder();
		columnNameList.append( " (" );
		columnValueList.append( " VALUES (" );

		boolean firstCol = true;
		for ( ColumnDefinition columnDef : columnsToAddInInsertStatement ) {
			if ( firstCol ) {
				firstCol = false;
			}
			else {
				columnNameList.append( ", " );
				columnValueList.append( ", " );
			}
			columnNameList.append( columnDef.getColumnName() );
			columnValueList.append( "?" );
		}
		columnNameList.append( ")" );
		columnValueList.append( ")" );

		query.append( columnNameList.toString() );
		query.append( columnValueList.toString() );

		return query.toString();
	}
	
	
}
